require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '254742063632',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'FLASH-MD',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AR: process.env.AUTO_REACTION || 'off',

    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMkF4SFlmOTRCeGg4THV4ejk4TlNKR3haS0ExSmFsVHl5RkxDTyt3eDRsUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS3ZWSjh5bmFGQmhZZXhZSTh0M2JJcnhyRlBmb0czSTM0QjQveG5DSjN3OD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIrR1NnaWRTa3FyWVM5dEdGS3FSaXBndVpQK3NLY0Jaa1BMNXpHTjVrR25VPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJKRHdya3lFSk5CRStKcEFOblFKdnQxWndLSVZKamhId0s5aWVYL0VmNGxVPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklBU2lQSE0wakVhdjZxaXhuTFNFbXVBYjZxOVpDUERhMGVBVE1NNTRrbkE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjR2bFhYcDZZSEtFdmJSd3VyMjROZk1QQ0FWVnhPbStpTHM5YVVQRGkwSG89In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYURBYkFBd1JBNVYxa1BZdzlEUGVJQlllaTdFSXFGVjd5N0plYjVTM3hGaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUW1zdE5zeG1tNUF5dzlqTDc0cHV3OG9PeWdLNVp1OFpmWTFrci92dCtEYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ill3VWdONWpjNkxPa2daMXE2Q3IvdGxKTlZhc3czWWdiazVUdzVLMHJGdDJ6U1BNZXhEU2JPdXg2dlVhOE9rUysvR1JISUNsaGpheURkdjlad1BndkN3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTEyLCJhZHZTZWNyZXRLZXkiOiJ2WndTd3dhbUttdktDTWtBL2ZuM21xakgvVEY3Q2JUeFhFRXRPRTlJLytBPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc5MjA1NzMwNkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJCMUI4MThEMDkzRDk4OTNFRUFDQUY2RjgyM0E1NDFEMSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzU0ODQ3NDc2fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3OTIwNTczMDZAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMkE1QTc0MUVDNUE0QjE1MDhCNEUwRkU1QTNFM0IwMkIifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1NDg0NzQ3OH1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiNEFHRzE2RFciLCJtZSI6eyJpZCI6IjI1NDc5MjA1NzMwNjoxM0BzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiJDbGludG9uIiwibGlkIjoiMjUxODc4NDkxMzUzMDkzOjEzQGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSWJjb2JvR0VOK3g0OFFHR0F3Z0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiZllCQjN6cUVhNnp6VDJ2Q2tSUm9hK0JLLytrZ2lLQlM1VElIVjE2TFVSZz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiQ0duWjhVblVLMTNzMmNrWnN4SmY0WVlJYnZ6N2JCQ0VkZTI0U0FYamRkUGFGM2lZOXZJOGpMelV5YUsyNFFGRzhTQ29kbUlCVDVhdGtkeFdyU21FRGc9PSIsImRldmljZVNpZ25hdHVyZSI6Ilo4NUQxS3NjUjY2cUFwYksrZ0xZWlFmdnVMZTh6Zk8rbGhVdlN5L2NkRnFzK1JjUlpsZ2RYN25YbTlZUlN4S1llcEczRXVaY1hpa0VHbzZKUHUycEFBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzkyMDU3MzA2OjEzQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlgyQVFkODZoR3VzODA5cndwRVVhR3ZnU3YvcElJaWdVdVV5QjFkZWkxRVkifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBMElDQT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc1NDg0NzQ3MCwibGFzdFByb3BIYXNoIjoiUFdrNUIiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUo4MyJ9',
    timezone: 'Africa/Nairobi',

    USER_LID: process.env.YOUR_LID, 

    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
